<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class CafeSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cafes')->insert([
            [
                'name' => "Paul's Coffee Roasters",
                'description' => 'Cosy coffee shop in Larnaca downtown. There are 5-7 well-known coffee origins, V60, Cold Brew and classic drinks. A small main hall and a large garden in the backyard. Few power outlets for digital nomads',
                'region' => 'Larnaca',
                'place_id' => 'ChIJGyOA68eD4BQRZtKA5kM_O0c',
                'url' => 'https://maps.google.com/?cid=5132765761181373030',
                'latitude' => '34.9143997',
                'longitude' => '33.634976',
            ],
            [
                'name' => 'Uluwatu Specialty Coffee',
                'description' => 'Large selection of coffee origins and comfortable sofas in the old town of Limassol. Few outlets only',
                'region' => 'Limassol',
                'place_id' => 'ChIJbSttYBsz5xQR1h0m6ubX9g0',
                'url' => 'https://maps.google.com/?cid=1006228953534701014',
                'latitude' => '34.675204',
                'longitude' => '33.04662',
            ],
            [
                'name' => 'South Coast Specialty Coffee',
                'description' => 'Large coffee shop in the Mackenzie beach area. Several classic coffee origins, tables with sockets and a separate playground for children',
                'region' => 'Larnaca',
                'place_id' => 'ChIJf2r8H92C4BQRClDxls7Viu4',
                'url' => 'https://maps.google.com/?cid=17188786011085295626',
                'latitude' => '34.889787',
                'longitude' => '33.6371021',
            ],
            [
                'name' => 'Menta Speciality CoffeeShop ',
                'description' => "A new coffee shop in town near the Christmas market. Delicious coffee made with Paul's Coffee Roasters beans. A covered terrace with a few tables is located behind the building",
                'region' => 'Larnaca',
                'place_id' => 'ChIJI3HxklcX3hQRHDVP87cbnIo',
                'url' => 'https://maps.google.com/?cid=9987888550475937052',
                'latitude' => '34.9122774',
                'longitude' => '33.6358878',
            ],
            [
                'name' => 'Kollaborative Coffee Roasters',
                'description' => 'Middle-size coffee shop and bar in Nicosia old town. Selection of coffee origins, few tables inside and outside',
                'region' => 'Nicosia',
                'place_id' => 'ChIJTf61IgAX3hQRCwEn_V1idxA',
                'url' => 'https://maps.google.com/?cid=1186525182654087435',
                'latitude' => '35.1671026',
                'longitude' => '33.3569759',
            ],
            [
                'name' => 'Nomad Bread & Coffee',
                'description' => 'Small takeaway coffee shop in Limassol centre with lots of coffee origins. No power sockets at all',
                'region' => 'Limassol',
                'place_id' => 'ChIJaWe7ozQz5xQRUKPzaPpiOCk',
                'url' => 'https://maps.google.com/?cid=2970232781892985680',
                'latitude' => '34.6830013',
                'longitude' => '33.04813059999999',
            ],
            [
                'name' => 'BREW LAB',
                'description' => 'Small takeaway coffee shop with two small verandas in the old town of Nicosia. No outlets',
                'region' => 'Nicosia',
                'place_id' => 'ChIJa39mz1kX3hQRdnH8Pdx2yAU',
                'url' => 'https://maps.google.com/?cid=416713653836607862',
                'latitude' => '35.1669308',
                'longitude' => '33.3582758',
            ],
            [
                'name' => 'The Daily Roast',
                'description' => 'Friendly coffee shop with smiling barista, breakfast and brunch. There are few tables with outlets inside and outside',
                'region' => 'Nicosia',
                'place_id' => 'ChIJ-_-vweMZ3hQRrS0J-nQjuuY',
                'url' => 'https://maps.google.com/?cid=16625639959709691309',
                'latitude' => '35.1582018',
                'longitude' => '33.3642074',
            ],
            [
                'name' => 'Bike & Bean Coffee Station',
                'description' => 'The sweet little coffee spot near the beach serves excellent speciality coffee by skilled baristas',
                'region' => 'Limassol',
                'place_id' => 'ChIJi4P5gf7N4BQRV19JRLjZOZ0',
                'url' => 'https://maps.google.com/?cid=11329325723070062423',
                'latitude' => '34.69403990000001',
                'longitude' => '33.0847664',
            ],
            [
                'name' => 'Cultivos Coffee',
                'description' => 'Third-wave specialty coffee shop in Paphos. Single-origin beans on the grinder are definitely recommended',
                'region' => 'Paphos',
                'place_id' => 'ChIJVbazMTYH5xQRa3_1yJp3QYc',
                'url' => 'https://maps.google.com/?cid=9746202575286665067',
                'latitude' => '34.7744771',
                'longitude' => '32.4283107',
            ],
            [
                'name' => 'Green Colibri',
                'description' => 'High-quality coffee and drinks to work, study, pass a day, and snack. Pleasant design and friendly staff',
                'region' => 'Nicosia',
                'place_id' => 'ChIJP2XvqN4X3hQRSJx83Z10fdM',
                'url' => 'https://maps.google.com/?cid=15239464935466245192',
                'latitude' => '35.1617596',
                'longitude' => '33.3646965',
            ],
            [
                'name' => 'A κχoffee project',
                'description' => 'Lovely coffee shop with a large selection of good coffee beans, pour-overs and a pleasant environment',
                'region' => 'Nicosia',
                'place_id' => 'ChIJF6t_GVwX3hQR72Mg8Uv5p1o',
                'url' => 'https://maps.google.com/?cid=6532463889087489007',
                'latitude' => '35.1664865',
                'longitude' => '33.3666372',
            ],
            [
                'name' => 'Nomad Bread & Coffee Germasogia',
                'description' => 'Tiny takeaway coffee shop opposite beach area with lots of coffee origins',
                'region' => 'Limassol',
                'place_id' => 'ChIJD9eSovjL4BQRH06tPeZARns',
                'url' => 'https://maps.google.com/?cid=8882858672656305695',
                'latitude' => '34.6996821',
                'longitude' => '33.09744450000001',
            ],
            [
                'name' => "Nick's coffee bike",
                'description' => 'Very cosy 2-story cafe with a friendly barista and a wide selection of coffee. There are sockets and desks on the 2nd floor',
                'region' => 'Larnaca',
                'place_id' => 'ChIJM7_dR9KD4BQRFHp1Z4CTNXE',
                'url' => 'https://maps.google.com/?cid=8157588479752370708',
                'latitude' => '34.9176959',
                'longitude' => '33.6327684',
            ],
            [
                'name' => 'The Shopkeeper & Co',
                'description' => 'Bizarre busy store and coffee bar',
                'region' => 'Limassol',
                'place_id' => 'ChIJEY-Nnxwz5xQRptn4sJVrQW0',
                'url' => 'https://maps.google.com/?cid=7872691914283735462',
                'latitude' => '34.6812041',
                'longitude' => '33.0454237',
            ],
            [
                'name' => 'DejaBrew Speciality Coffee',
                'description' => 'Coffee roaster and coffee store',
                'region' => 'Limassol',
                'place_id' => 'ChIJHdMhqtYz5xQRtXJ3NzfOGGQ',
                'url' => 'https://maps.google.com/?cid=7212741539782947509',
                'latitude' => '34.6912742',
                'longitude' => '33.0446085',
            ],
            [
                'name' => 'Tribe Coffee Roasters',
                'description' => 'Coffee Roasters',
                'region' => 'Limassol',
                'place_id' => 'ChIJTWSzFg4z5xQRYIfzo8CtQQA',
                'url' => 'https://maps.google.com/?cid=18486916382164832',
                'latitude' => '34.6887849',
                'longitude' => '33.044686',
            ],
            [
                'name' => 'Beanhaus Coffee Roasters',
                'description' => 'Coffee Roasters',
                'region' => 'Paphos',
                'place_id' => 'ChIJV_gcY_QG5xQRCJM84hwoQ6Y',
                'url' => 'https://maps.google.com/?cid=11980463538255467272',
                'latitude' => '34.775349',
                'longitude' => '32.4209081',
            ],
            [
                'name' => 'UTU Specialty Coffee',
                'description' => 'New tiny coffee shop in town. Try the origami coffee :-)',
                'region' => 'Nicosia',
                'place_id' => 'ChIJEe2tD5cX3hQR-YQGWRv379k',
                'url' => 'https://maps.google.com/?cid=15704042122493986041',
                'latitude' => '35.1684952',
                'longitude' => '33.3582323',
            ],
            [
                'name' => 'Wagmi coffee',
                'description' => 'A new large coffee shop in the old town with experienced baristas and a varied beverage menu',
                'region' => 'Limassol',
                'place_id' => 'ChIJewyjOR8z5xQR1z6IckS_PI8',
                'url' => 'https://maps.google.com/?cid=10321334746726547159',
                'latitude' => '34.6751652',
                'longitude' => '33.0460581',
            ],
            [
                'name' => 'SENIMAN Coffee Shop',
                'description' => 'Good regular coffee and very tasty roasted coffee beans',
                'region' => 'Nicosia',
                'place_id' => 'ChIJIz-0Mk4Z3hQR8bksmhUtigI',
                'url' => 'https://maps.google.com/?cid=183008305666111985',
                'latitude' => '35.1619516',
                'longitude' => '33.3634972',
            ],
            [
                'name' => 'Brew Story',
                'description' => "Fresh and little coffee shop in Nicosia's centre. Several tables both indoors and outside",
                'region' => 'Nicosia',
                'place_id' => 'ChIJAaH8iuUX3hQR1lkyOy94fLg',
                'url' => 'https://maps.google.com/?cid=13293632344342813142',
                'latitude' => 35.1657465,
                'longitude' => 33.358005,
            ],
            [
                'name' => 'Localito Specialty Coffee',
                'description' => "Paphos's newest coffee shop, featuring BeanHaus beans. try it!",
                'region' => 'Paphos',
                'place_id' => 'ChIJybWRnfgX5xQRKncxplIhl8M',
                'url' => 'https://maps.google.com/?cid=14093770197738551082',
                'latitude' => 34.7747226,
                'longitude' => 32.4278571,
            ],
            [
                'name' => 'Nomad Bread & Coffee',
                'description' => 'The third location of the famous coffee chain',
                'region' => 'Limassol',
                'place_id' => 'ChIJQe38LdIz5xQR8iT0WWNTcDc',
                'url' => 'https://maps.google.com/?cid=3994784555653670130',
                'latitude' => 34.6860825,
                'longitude' => 33.0486783,
            ],
            [
                'name' => 'Nomad Bread & Coffee',
                'description' => 'Nicosia shop of the famous coffee chain',
                'region' => 'Nicosia',
                'place_id' => 'ChIJZ8IQN4MX3hQRXyoKoOXI2gc',
                'url' => 'https://maps.google.com/?cid=565985591746505311',
                'latitude' => 35.1673995,
                'longitude' => 33.3676912,
            ],
            [
                'name' => 'Samba Coffee Roasters Cyprus',
                'description' => 'Coffee wholesaler',
                'region' => 'Limassol',
                'place_id' => 'ChIJCemF_r0z5xQRiSA9yv6wg2s',
                'url' => 'https://maps.google.com/?cid=7747230392368570505',
                'latitude' => 34.6971016,
                'longitude' => 33.0518579,
            ],
        ]);
    }
}
