app = "specialty-api"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[processes]
app = "php-fpm --daemonize"
web = "nginx -g 'daemon off;'"

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["web"]

[[services.ports]]
port = 443
handlers = ["tls"]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.http_checks]]
interval = "10s"
timeout = "1s"
grace_period = "5s"
restart_limit = 0
method = "get"
path = "/cafes/random"
protocol = "http"
