app = "specialty-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build.args]
DB_CONNECTION = "sqlite"

[env]
APP_ENV = "production"
APP_NAME = "Specialty Coffee in Cyprus"
APP_URL = "https://api.specialtycoffee.cy"
APP_URL_INSECURE = "http://api.specialtycoffee.cy"
CORS_ORIGIN = "https://specialtycoffee.cy"
DB_CONNECTION = "sqlite"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
PRIMARY_REGION = "fra"
SENTRY_SEND_DEFAULT_PII = "true"
SENTRY_TRACES_SAMPLE_RATE = 1.0

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "5s"
interval = "10s"
restart_limit = 0
timeout = "1s"
